include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    unnecessary_import: ignore
    use_super_parameters: ignore
    prefer_const_declarations: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
